# Generated by Django 5.1.5 on 2025-03-19 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programminglanguage_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('PRACTISE_INTERVIEW', 'Practise_Interview'), ('FOLLOWUP_INTERVIEW', 'Followup_Interview'), ('SPECIFIC_ROLE_INTERVIEW', 'Specific_Role_Interview'), ('RAPID_FIRE', 'Rapid_Fire_Interview'), ('CODE_QUIZ', 'Code_Quiz'), ('RESUME', 'Resume_Analysis'), ('GROUP_DISCUSSION', 'Group Discussion')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
