# Generated by Django 5.1.5 on 2025-03-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_debateentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('complaint_type', models.CharField(choices=[('GD', 'General Complaint'), ('Debate', 'Debate Complaint'), ('Platform', 'Platform Complaint')], max_length=20)),
                ('description', models.TextField()),
                ('violence_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
